name: Test and publish
on:
  push:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  test:
    name: Test and publish the book
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:TL2015-historic
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install additional packages
        run: |
          set -ex
          apt-get -qy update
          apt-get -qy install curl groff-base groff inkscape python3-proselint python3-pygments trang

      - name: Run Proselint
        run: make test

      - name: Typeset the book
        run: make

      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            main.pdf

      - name: Create a release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest typeset book
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            main.pdf
